---
- hosts: all
  user: vagrant
  become: yes
  vars:
    project_dir: /home/ansibleProject
  tasks:
    - name: Updating our cache
      apt: update_cache=yes cache_valid_time=86400
  
    - name: Install required packages
      apt:
        name: 
          - nginx
          - python-pip
          - python3
          - python3-pip

    - name: Installing crontab
      pip:
          name: python-crontab
          executable: pip3

    - name: Create project directory
      file: path={{project_dir}} state=directory    

    - name: Start nginx
      service:
          name=nginx state=started

    - name: Copy nginx config
      template: src=nginx.conf  dest=/etc/nginx/nginx.conf
      notify: 
          - Restart Nginx

    - name: Copy cron script
      copy: src=cron.py  dest={{ project_dir }}/cron.py  mode=0755
      notify:
          - Start cron

    - name: Copy service_state file
      copy: src=service_state  dest={{ project_dir }}/service_state
      notify: 
           - Restart Nginx
           - Copy service state
           - Start cron

  handlers:
    - name: Restart Nginx
      service: name=nginx state=restarted
    - name: Start cron
      command: python3 {{ project_dir }}/cron.py     
    - name: Copy service state
      command: cp {{ project_dir }}/service_state /opt/service_state 
